spring.application.name=job-tracker-api
spring.datasource.url=jdbc:mysql://localhost:3306/job_tracker?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Mehadi786
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
